version: '3.9'

services:
  
  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: app-Dockerfile
      args:
         - GIT_COMMIT_HASH
    image: casca113s2/phonebook:${GIT_COMMIT_HASH}
    restart: always
    ports:
      - "5000:8000"
    network_mode: host