name: Build Trigger

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: 
      group: self-hosted
      labels: runner1
    steps:
    - name: Build
      uses: appleboy/jenkins-action@master
      with:
        url: http://10.10.31.212:8080
        user: "casca113s2"
        token: ${{ secrets.TOKEN }}
        job: "postgreSQL-python-pipeline"
